[package]
name = "particle_generator"
version = "0.1.0"
authors = ["n3f4s <tiv.crb@gmail.com>"]

[dependencies]
#sdl2 = "*"
rand = "0.3"
rayon = "*"
num-traits = "*"
num = "*"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
features = ["image", "gfx", "ttf"]
